export const PERMISSION_CATALOG = [
  { key: "admin.dashboard.view", description: "Access the SuperAdmin dashboard homepage and overview cards." },
  { key: "admin.dashboard.analytics.view", description: "View dashboard analytics, counters, and summary widgets." },
  { key: "admin.profile.view.self", description: "View own SuperAdmin profile." },
  { key: "admin.profile.edit.self", description: "Edit own SuperAdmin profile." },
  { key: "users.view", description: "View user listing in admin portal." },
  { key: "users.view.detail", description: "View full user details, profile, and account metadata." },
  { key: "users.search", description: "Search and filter users." },
  { key: "users.status.manage", description: "Suspend, activate, or otherwise change user account status." },
  { key: "users.role.assign", description: "Assign roles to users." },
  { key: "users.role.remove", description: "Remove roles from users." },
  { key: "users.access.audit", description: "Review user activity and account access state." },
  { key: "verification.queue.view", description: "View lawyer verification queue." },
  { key: "verification.request.view", description: "Open a single lawyer verification request." },
  { key: "verification.approve", description: "Approve a lawyer verification request." },
  { key: "verification.reject", description: "Reject a lawyer verification request." },
  { key: "verification.note.manage", description: "Add or update admin verification notes." },
  { key: "moderation.queue.view", description: "View moderation queues, flagged content, and user reports." },
  { key: "moderation.report.view", description: "View a specific moderation report or flagged item." },
  { key: "moderation.resolve", description: "Mark reports or moderation cases as resolved." },
  { key: "moderation.remove_content", description: "Remove discussion, answer, comment, or case content through moderation action." },
  { key: "moderation.warn_user", description: "Issue warning or moderation action against user." },
  { key: "moderation.archive_content", description: "Archive or hide content from public view." },
  { key: "reports.view", description: "Access reports and insights screens." },
  { key: "reports.analytics.view", description: "View reporting charts, trend summaries, and metrics." },
  { key: "reports.export", description: "Export reports to PDF or downloadable format." },
  { key: "settings.view", description: "Access admin settings area." },
  { key: "settings.edit", description: "Modify admin settings and configuration values." },
  { key: "roles.view", description: "View all roles in the system." },
  { key: "roles.create", description: "Create new roles." },
  { key: "roles.edit", description: "Edit role names and descriptions." },
  { key: "roles.delete", description: "Delete non-system roles." },
  { key: "permissions.view", description: "View all permissions in the system." },
  { key: "permissions.create", description: "Create new permissions." },
  { key: "permissions.edit", description: "Edit permission definitions." },
  { key: "permissions.delete", description: "Delete unused permissions." },
  { key: "role_permissions.view", description: "View permission assignments for roles." },
  { key: "role_permissions.manage", description: "Assign or remove permissions for roles." },
  { key: "user_roles.view", description: "View role assignments for users." },
  { key: "user_roles.manage", description: "Assign or remove roles from users." },
  { key: "cases.review.queue.view", description: "View case review queue in admin portal." },
  { key: "cases.review.detail.view", description: "Open detailed review page for a case." },
  { key: "cases.review.publish", description: "Publish a reviewed case record." },
  { key: "cases.review.reject", description: "Reject a case and send it back for changes." },
  { key: "cases.review.archive", description: "Archive or remove a case from active repository." },
  { key: "cases.review.note.manage", description: "Add or update reviewer notes on a case." },
  { key: "cases.review.status.manage", description: "Change case workflow status during admin review." },
  { key: "discussions.admin.view_all", description: "View all discussions including moderated or restricted content." },
  { key: "cases.admin.view_all", description: "View all cases including non-public workflow states." },
  { key: "profiles.admin.view_all", description: "View all user profiles with admin oversight access." },
  { key: "notifications.admin.audit", description: "Audit notification-related system behavior if needed." },
  { key: "auth.login", description: "Sign in to LawyerUser portal." },
  { key: "auth.logout", description: "Sign out from LawyerUser portal." },
  { key: "auth.register", description: "Register a LawyerUser account." },
  { key: "auth.password.reset", description: "Request password reset and set new password." },
  { key: "auth.email.verify", description: "Verify account email." },
  { key: "account.view.self", description: "View own account/session details." },
  { key: "account.edit.self", description: "Update own basic account details." },
  { key: "account.password.change.self", description: "Change own password." },
  { key: "profile.view.self", description: "View own lawyer profile." },
  { key: "profile.setup.self", description: "Access profile setup flow." },
  { key: "profile.edit.self", description: "Edit own professional profile." },
  { key: "profile.stats.view.self", description: "View own profile statistics and analytics." },
  { key: "profile.visibility.manage.self", description: "Manage visibility settings for own profile sections." },
  { key: "profile.public.view", description: "View public lawyer/member profiles." },
  { key: "profile.view.track", description: "Record and track profile views." },
  { key: "discussions.view", description: "View discussions listing and detail pages." },
  { key: "discussions.create", description: "Create a new discussion." },
  { key: "discussions.edit.own", description: "Edit own discussion." },
  { key: "discussions.delete.own", description: "Soft delete own discussion." },
  { key: "discussions.view.own", description: "View own created discussions in My Discussions / Topics area." },
  { key: "discussions.view.saved_own", description: "View own saved discussions." },
  { key: "discussions.bookmark", description: "Save or unsave a discussion." },
  { key: "discussions.follow", description: "Follow or unfollow a discussion." },
  { key: "discussions.react", description: "React to a discussion with vote or emoji." },
  { key: "discussions.ai_summary.view", description: "View AI summary for a discussion when available." },
  { key: "answers.view", description: "View answers under a discussion." },
  { key: "answers.create", description: "Post an answer to a discussion." },
  { key: "answers.react", description: "React to an answer." },
  { key: "answers.accept.on_own_discussion", description: "Accept an answer on a discussion owned by the current LawyerUser." },
  { key: "comments.view", description: "View discussion and answer comments." },
  { key: "comments.create", description: "Post comment or reply on discussion/answer threads." },
  { key: "comments.react", description: "React to comments." },
  { key: "notifications.view.self", description: "View own notifications." },
  { key: "notifications.mark_read.self", description: "Mark own notifications as read." },
  { key: "cases.view", description: "View case repository listing and public case details." },
  { key: "cases.meta.view", description: "View case repository filter metadata such as categories, tags, courts, and regions." },
  { key: "cases.create.draft", description: "Create a new case draft." },
  { key: "cases.view.own_dashboard", description: "View own case board / My Cases screen." },
  { key: "cases.view.own_unpublished", description: "View own draft, rejected, and pending-review case records." },
  { key: "cases.edit.own", description: "Edit own case draft or own editable case record." },
  { key: "cases.submit.own_for_review", description: "Submit own draft or rejected case for admin review." },
  { key: "cases.bookmark", description: "Save or unsave case records." },
  { key: "cases.view.saved_own", description: "View own saved case collection." },
  { key: "cases.share", description: "Share case record links." },
  { key: "saved.view.self", description: "Access personal saved workspace modules." },
  { key: "topics.view.self", description: "Access own discussion topics / My Discussions module." },
] as const;

export const LAWYER_PERMISSION_KEYS = [
  "auth.login",
  "auth.logout",
  "auth.register",
  "auth.password.reset",
  "auth.email.verify",
  "account.view.self",
  "account.edit.self",
  "account.password.change.self",
  "profile.view.self",
  "profile.setup.self",
  "profile.edit.self",
  "profile.stats.view.self",
  "profile.visibility.manage.self",
  "profile.public.view",
  "profile.view.track",
  "discussions.view",
  "discussions.create",
  "discussions.edit.own",
  "discussions.delete.own",
  "discussions.view.own",
  "discussions.view.saved_own",
  "discussions.bookmark",
  "discussions.follow",
  "discussions.react",
  "discussions.ai_summary.view",
  "answers.view",
  "answers.create",
  "answers.react",
  "answers.accept.on_own_discussion",
  "comments.view",
  "comments.create",
  "comments.react",
  "notifications.view.self",
  "notifications.mark_read.self",
  "cases.view",
  "cases.meta.view",
  "cases.create.draft",
  "cases.view.own_dashboard",
  "cases.view.own_unpublished",
  "cases.edit.own",
  "cases.submit.own_for_review",
  "cases.bookmark",
  "cases.view.saved_own",
  "cases.share",
  "saved.view.self",
  "topics.view.self",
] as const;

export const ROLE_CATALOG = [
  { name: "SuperAdmin", description: "Business role with full platform administration access.", isSystem: true },
  { name: "LawyerUser", description: "Business role for lawyer portal access.", isSystem: true },
  { name: "admin", description: "Technical compatibility alias for SuperAdmin.", isSystem: true },
  { name: "lawyer", description: "Technical compatibility alias for LawyerUser.", isSystem: true },
  { name: "member", description: "Default member role.", isSystem: true },
  { name: "moderator", description: "Content moderator role.", isSystem: true },
] as const;

export const ROLE_PERMISSION_ASSIGNMENTS: Record<string, string[]> = {
  SuperAdmin: PERMISSION_CATALOG.map((permission) => permission.key),
  LawyerUser: [...LAWYER_PERMISSION_KEYS],
  admin: PERMISSION_CATALOG.map((permission) => permission.key),
  lawyer: [...LAWYER_PERMISSION_KEYS],
};

export const BUSINESS_ROLE_TO_TECHNICAL_ROLE = {
  SuperAdmin: "admin",
  LawyerUser: "lawyer",
} as const;
